language: rust
sudo: false
rust:
  - beta
  - stable
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --all
env:
  global:
    - RUST_BACKTRACE=1